### PR TITLE
Perbaikan halaman Docusaurus

### PR DESCRIPTION
**Pull request by kudaliar032**
- Perbaikan path yang dikonversi menjadi lowercase https://github.com/BlankOn/wiki/issues/111
- Menambahkan glosarium dan beberapa penyesuaian pada bilah samping
- Menambahkan tautan [GitHub](https://github.com/BlankOn/wiki) pada navbar
- Perbaikan beberapa URL pada halaman wiki

Pratinjau: https://vigorous-booth-22939e.netlify.app

### CODE REVIEW

**Review by herpiko — CHANGES_REQUESTED** [review]
@kudaliar032 Thanks.

This repository is intended as `documentation`, not app with its source code. Any contributor from documentation team (most of them are not programmer) should get the documentation immediately, not this source code. Could you preserve the path of the wiki? It's the docusaurus things that need to be contained in it's own directory instead the wiki itself.

**Comment by kudaliar032** [comment]
Unfortunately for now docusaurus doesn't support root path as the path that contains documentation by default. I will close this Pull Request, and look for another solution. thank you @herpiko

**Comment by herpiko** [comment]
@kudaliar032 it's still possible to do this on CI job side. I'll try to look at it as well.

**Comment by herpiko** [comment]
@kudaliar032 as you have been digging on docusaurus, I've some questions.

Are these lines required for each markdown files? What is it accomplish?

```
---
slug: /
title: Selamat Datang
hide_title: true
---
```

**Comment by kudaliar032** [comment]
@herpiko no, it's not required. It is needed only if you want to modify the url slug or title of the page

**Pull request closed without merging**
